default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'finestkind*' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>

development:
  <<: *default
  database: deeder_development

test:
  <<: *default
  database: deeder_test

production:
  <<: *default
  # database: deeder_production
  # username: <%= ENV['POSTGRES_USER'] %>
  # password: <%= ENV['POSTGRES_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
