default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: deeder_development

test:
  <<: *default
  database: deeder_test

production:
  <<: *default
  url: postgresql://deeder_user:OC0KfLAfA7wPuUrZINfrM1jwKaIg7ga0@dpg-cvelt8dsvqrc73fc1g1g-a/deeder
  database: deeder
  username: deeder_user
  password: OC0KfLAfA7wPuUrZINfrM1jwKaIg7ga0
  host: dpg-cvelt8dsvqrc73fc1g1g-a

queue:
  <<: *default
  database: solid_queue
  username: deeder_user
  password: OC0KfLAfA7wPuUrZINfrM1jwKaIg7ga0
  host: dpg-cvelt8dsvqrc73fc1g1g-a
  migrations_paths: db/solid_queue_migrations
