default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: deeder_development

test:
  <<: *default
  database: deeder_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
