default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 100
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 2) %>
      polling_interval: 0.1
      concurrency_limits:
        SolidQueue::Execution: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  dispatchers:
    - polling_interval: 0.5
      batch_size: 500
  workers:
    - queues: "critical,default"
      threads: 5
      processes: 2
      polling_interval: 0.1
    - queues: "low_priority,analytics"
      threads: 2
      processes: 1
      polling_interval: 2.0

services:
  - type: web
    name: web
    buildCommand: bundle install && rails assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
  - type: worker
    name: jobs
    startCommand: bundle exec solid_queue
    envVars:
      - key: JOB_CONCURRENCY
        value: 3
